const SupportPoint = [
  {key: '1', value: 'APODI'},
  {key: '2', value: 'AREIA BRANCA'},
  {key: '3', value: 'ASSÚ'},
  {key: '4', value: 'BARAÚNA'},
  {key: '5', value: 'CAICÓ'},
  {key: '6', value: 'CANGUARETAMA'},
  {key: '7', value: 'CEARÁ MIRIM'},
  {key: '8', value: 'CEPE'},
  {key: '9', value: 'CURRAIS NOVOS'},
  {key: '10', value: 'EXTREMOZ'},
  {key: '11', value: 'GOIANINHA'},
  {key: '12', value: 'JOÃO CÂMARA'},
  {key: '13', value: 'LAJES'},
  {key: '14', value: 'MACAU'},
  {key: '15', value: 'MONTE ALEGRE'},
  {key: '16', value: 'NÍSIA FLORESTA'},
  {key: '17', value: 'NOVA CRUZ'},
  {key: '18', value: 'PARELHAS'},
  {key: '19', value: 'PARNAMIRIM I'},
  {key: '20', value: 'PARNAMIRIM II'},
  {key: '21', value: 'PATU'},
  {key: '22', value: 'PAU DOS FERROS'},
  {key: '23', value: 'SANTA CRUZ'},
  {key: '24', value: 'SANTO ANTÔNIO'},
  {key: '25', value: 'SÃO JOSÉ DO MIBIPU'},
  {key: '26', value: 'SÃO PAULO POTENGI'},
  {key: '27', value: 'SÃO GONÇALO DO AMARANTE I'},
  {key: '28', value: 'SÃO GONÇALO DO AMARANTE II'},
  {key: '29', value: 'STERBOM I'},
  {key: '30', value: 'STERBOM II'},
  {key: '31', value: 'OUTRA'},
];

export default SupportPoint;
